# Generated by Django 3.2.9 on 2021-11-06 19:38

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_info',
            fields=[
                ('nsu_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('new_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='nsu_id')),
            ],
        ),
        migrations.CreateModel(
            name='Ssc_equivlent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=100)),
                ('passing_year', models.CharField(max_length=100)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('medium', models.CharField(max_length=100)),
                ('board', models.CharField(max_length=100)),
                ('newd_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='nsu_id')),
                ('nsu_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entries.student_info')),
            ],
        ),
        migrations.CreateModel(
            name='Semester_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(max_length=100)),
                ('semester_year', models.DateField()),
                ('semester_gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('semester_cedit', models.CharField(max_length=100)),
                ('newg_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='nsu_id')),
                ('nsu_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entries.student_info')),
            ],
        ),
        migrations.CreateModel(
            name='Personal_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathers_name', models.CharField(max_length=100)),
                ('mothers_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=10)),
                ('citizenship', models.CharField(max_length=10)),
                ('marital_status', models.CharField(max_length=10)),
                ('blood_group', models.CharField(max_length=10)),
                ('covid19_status', models.CharField(choices=[('taken', 'taken'), ('not taken', 'not taken'), ('registered', 'registered'), ('not registered', 'not registered')], max_length=50)),
                ('contact_number', models.CharField(max_length=20)),
                ('news_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='nsu_id')),
                ('nsu_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entries.student_info')),
            ],
        ),
        migrations.CreateModel(
            name='Hsc_equivlent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collage_name', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=100)),
                ('passing_year', models.CharField(max_length=100)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('medium', models.CharField(max_length=100)),
                ('board', models.CharField(max_length=100)),
                ('newf_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='nsu_id')),
                ('nsu_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entries.student_info')),
            ],
        ),
        migrations.CreateModel(
            name='Financial_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_income', models.CharField(max_length=100)),
                ('earning_source', models.CharField(max_length=100)),
                ('newh_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='nsu_id')),
                ('nsu_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entries.student_info')),
            ],
        ),
    ]
