# Generated by Django 3.2.9 on 2021-11-13 18:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('couse_code', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('course_title', models.CharField(max_length=100)),
                ('course_desc', models.TextField(max_length=100)),
                ('course_credit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_info',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nsu_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Financial_history',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='entries.student_info')),
                ('annual_income', models.IntegerField()),
                ('earning_source', models.CharField(max_length=100)),
                ('annual_expenditure', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Hsc_equivlent',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='entries.student_info')),
                ('collage_name', models.CharField(max_length=100)),
                ('session', models.IntegerField()),
                ('passing_year', models.IntegerField()),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('medium', models.CharField(max_length=100)),
                ('board', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_info',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='entries.student_info')),
                ('fathers_name', models.CharField(max_length=100)),
                ('mothers_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=20)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField(max_length=100)),
                ('religion', models.CharField(max_length=10)),
                ('citizenship', models.CharField(max_length=10)),
                ('marital_status', models.CharField(choices=[('MARRIED', 'MARRIED'), ('UNMARRIED', 'UNMARRIED')], max_length=20)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('O+', 'O+'), ('A-', 'A-'), ('B-', 'B-'), ('O-', 'O-'), ('AB-', 'AB-')], max_length=20)),
                ('covid19_status', models.CharField(choices=[('Taken', 'Taken'), ('Not taken', 'Not taken')], max_length=20)),
                ('contact_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ssc_equivlent',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='entries.student_info')),
                ('school_name', models.CharField(max_length=100)),
                ('session', models.IntegerField()),
                ('passing_year', models.IntegerField()),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('medium', models.CharField(max_length=100)),
                ('board', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='entries.student_info')),
                ('semester', models.CharField(choices=[('SUMMER', 'SUMMER'), ('FALL', 'FALL'), ('SPRING', 'SPRING')], max_length=20)),
                ('year', models.IntegerField()),
                ('grade', models.CharField(choices=[('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('F', 'F'), ('I', 'I'), ('W', 'W')], max_length=10)),
                ('course_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entries.course')),
            ],
        ),
    ]
