# Generated by Django 3.2.9 on 2021-11-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_info',
            name='photo',
        ),
        migrations.AddField(
            model_name='financial_history',
            name='No_of_earning_person',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial_history',
            name='annua_expenditure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('O+', 'O+'), ('A-', 'A-'), ('B-', 'B-'), ('O-', 'O-'), ('AB-', 'AB-')], max_length=10),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=10),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='marital_status',
            field=models.CharField(choices=[('MARRIED', 'MARRIED'), ('SINGLE', 'SINGLE'), ('DIVORCE', 'DIVORCE'), ('COMPLICATED', 'COMPLICATED')], max_length=100),
        ),
        migrations.AlterField(
            model_name='semester_history',
            name='semester_name',
            field=models.CharField(choices=[('SUMMER', 'SUMMER'), ('FALL', 'FALL'), ('SPRING', 'SPRING')], max_length=100),
        ),
    ]
