# Generated by Django 3.2.9 on 2021-11-19 14:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financial_info',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='entries.student_info')),
                ('annual_income', models.IntegerField(blank=True, null=True)),
                ('earning_source', models.CharField(blank=True, max_length=100, null=True)),
                ('annual_expenditure', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='hsc_equivlent',
            name='collage_name',
        ),
        migrations.RemoveField(
            model_name='personal_info',
            name='covid19_status',
        ),
        migrations.RemoveField(
            model_name='personal_info',
            name='fathers_name',
        ),
        migrations.RemoveField(
            model_name='personal_info',
            name='mothers_name',
        ),
        migrations.AddField(
            model_name='grade',
            name='stu_ui',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.student_info'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hsc_equivlent',
            name='college_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='covid19_vax_status',
            field=models.CharField(blank=True, choices=[('Vaccinated', 'Vaccinated'), ('Unvaccinated', 'Unvaccinated')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='batch',
            field=models.CharField(max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_info',
            name='dept',
            field=models.CharField(max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_info',
            name='program',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='course_credit',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_desc',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='course_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entries.course'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('F', 'F'), ('I', 'I'), ('W', 'W')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='semester',
            field=models.CharField(blank=True, choices=[('SUMMER', 'SUMMER'), ('FALL', 'FALL'), ('SPRING', 'SPRING')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hsc_equivlent',
            name='board',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hsc_equivlent',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='hsc_equivlent',
            name='medium',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hsc_equivlent',
            name='passing_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hsc_equivlent',
            name='session',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='address',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('O+', 'O+'), ('A-', 'A-'), ('B-', 'B-'), ('O-', 'O-'), ('AB-', 'AB-')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='citizenship',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Married', 'Married'), ('Unmarried', 'Unmarried')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='religion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ssc_equivlent',
            name='board',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ssc_equivlent',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='ssc_equivlent',
            name='medium',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ssc_equivlent',
            name='passing_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ssc_equivlent',
            name='school_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ssc_equivlent',
            name='session',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='nsu_id',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='photo',
            field=models.ImageField(default='photos/profile-picture-default.png', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='Financial_history',
        ),
    ]
