# Generated by Django 3.2.9 on 2021-11-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20211107_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
