# Generated by Django 3.2.9 on 2021-11-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_alter_student_info_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
