# Generated by Django 3.2.9 on 2021-11-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_auto_20211119_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='stu_ui',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='entry_id',
        ),
        migrations.AddField(
            model_name='grade',
            name='ga_id',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
