# Generated by Django 3.2.9 on 2021-11-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_student_info_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financial_history',
            old_name='annua_expenditure',
            new_name='annual_expenditure',
        ),
        migrations.AlterField(
            model_name='student_info',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
