# Generated by Django 3.2.9 on 2021-11-18 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0009_auto_20211114_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hsc_equivlent',
            old_name='collage_name',
            new_name='college_name',
        ),
    ]
