# Generated by Django 3.2.9 on 2021-11-18 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0010_rename_collage_name_hsc_equivlent_college_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Financial_history',
            new_name='Financial_info',
        ),
        migrations.RenameField(
            model_name='personal_info',
            old_name='fathers_name',
            new_name='father_name',
        ),
        migrations.RenameField(
            model_name='personal_info',
            old_name='mothers_name',
            new_name='mother_name',
        ),
        migrations.RemoveField(
            model_name='personal_info',
            name='covid19_status',
        ),
        migrations.AddField(
            model_name='personal_info',
            name='covid19_vax_status',
            field=models.CharField(blank=True, choices=[('Vaccinated', 'Vaccinated'), ('Unvaccinated', 'Unvaccinated')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='batch',
            field=models.CharField(default='182', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_info',
            name='dept',
            field=models.CharField(default='ECE', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_info',
            name='program',
            field=models.CharField(default='CSE', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='course_credit',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Married', 'Married'), ('Unmarried', 'Unmarried')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='nsu_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
