# Generated by Django 3.2.9 on 2021-11-18 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0011_auto_20211118_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='nsu_id',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='photo',
            field=models.ImageField(default='photos/profile-picture-default.png', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
